"""initial schema

Revision ID: 1e6e7fc1f721
Revises: 
Create Date: 2026-10-03 14:15:22.780910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.config import get_settings
from app.core.db import create_virtual_tables


# revision identifiers, used by Alembic.
revision: str = '1e6e7fc1f721'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discord_channel_feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild_id', sa.String(length=64), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('filter_expr', sa.Text(), nullable=False),
    sa.Column('filter_ast', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'filter_expr')
    )
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('domains', sa.JSON(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_people_slug'), ['slug'], unique=True)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('domain', 'topic', 'entity', 'ticker', name='tagkind'), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'slug')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_slug'), ['slug'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('discord_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'podcast', 'blog', 'arxiv', 'reddit', 'x', name='platform'), nullable=False),
    sa.Column('handle', sa.String(length=500), nullable=False),
    sa.Column('poll_interval_min', sa.Integer(), nullable=False),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cursor', sa.String(length=500), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'handle')
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_person_id'), ['person_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('filter_expr', sa.Text(), nullable=False),
    sa.Column('filter_ast', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('rss_token', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rss_token')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    op.create_table('media_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('youtube', 'podcast', 'blog', 'arxiv', 'reddit', 'x', name='platform'), nullable=False),
    sa.Column('external_id', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'fetched', 'triaged', 'extracted', 'skipped', 'failed', name='mediastatus'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('llm_usage', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'external_id')
    )
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_items_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_items_status'), ['status'], unique=False)

    op.create_table('viewpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_item_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('claim', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('quote_timestamp', sa.Integer(), nullable=True),
    sa.Column('stance', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('novelty_score', sa.Float(), nullable=False),
    sa.Column('repeat_of_id', sa.Integer(), nullable=True),
    sa.Column('quote_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_item_id'], ['media_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repeat_of_id'], ['viewpoints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('viewpoints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_viewpoints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewpoints_media_item_id'), ['media_item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_viewpoints_person_id'), ['person_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('viewpoint_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['viewpoint_id'], ['viewpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target', 'viewpoint_id', 'channel')
    )
    op.create_table('viewpoint_tags',
    sa.Column('viewpoint_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['viewpoint_id'], ['viewpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('viewpoint_id', 'tag_id')
    )
    # ### end Alembic commands ###
    create_virtual_tables(op.get_bind(), get_settings().embedding_dim)


def downgrade() -> None:
    for t in ('viewpoints_ai', 'viewpoints_ad', 'viewpoints_au'):
        op.execute(f'DROP TRIGGER IF EXISTS {t}')
    op.execute('DROP TABLE IF EXISTS viewpoint_fts')
    op.execute('DROP TABLE IF EXISTS viewpoint_vec')
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('viewpoint_tags')
    op.drop_table('deliveries')
    with op.batch_alter_table('viewpoints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_viewpoints_person_id'))
        batch_op.drop_index(batch_op.f('ix_viewpoints_media_item_id'))
        batch_op.drop_index(batch_op.f('ix_viewpoints_created_at'))

    op.drop_table('viewpoints')
    with op.batch_alter_table('media_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_items_status'))
        batch_op.drop_index(batch_op.f('ix_media_items_source_id'))
        batch_op.drop_index(batch_op.f('ix_media_items_published_at'))

    op.drop_table('media_items')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_person_id'))

    op.drop_table('sources')
    op.drop_table('users')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_slug'))

    op.drop_table('tags')
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_people_slug'))

    op.drop_table('people')
    op.drop_table('discord_channel_feeds')
    # ### end Alembic commands ###
