"""viewpoint quote_translation

Revision ID: 611f9160ddf2
Revises: dc89a00d95f7
Create Date: 2026-10-03 16:28:14.232991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '611f9160ddf2'
down_revision: Union[str, Sequence[str], None] = 'dc89a00d95f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quote_translation', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('viewpoints', schema=None) as batch_op:
        batch_op.drop_column('quote_translation')

    # ### end Alembic commands ###
